# Generated by Django 4.2.1 on 2023-05-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='responsavel',
            field=models.ManyToManyField(related_name='produtos', to='core0.responsavel'),
        ),
    ]
